DATASET_DEFAULTS = {
    "HandWritten": dict(
        in_dim=[240, 76, 216, 47, 64],
        num_sample=2000,
        num_classes=10,
        num_views=5,
        batch_size=256,
        using_tsne=True,
    ),
    "aloideep3v": dict(
        in_dim=[2048, 4096, 2048],
        num_sample=10800,
        num_classes=100,
        num_views=3,
        batch_size=256,
        using_tsne=False,
    ),
    "Caltech101-7": dict(
        in_dim=[48, 40, 254, 1984, 512, 928],
        num_sample=1474,
        num_classes=7,
        num_views=6,
        batch_size=512,
        using_tsne=False,
    ),
    "Scene-15": dict(
        in_dim=[20, 59, 40],
        num_sample=4485,
        num_classes=15,
        num_views=3,
        batch_size=512,
        using_tsne=False,
    ),
    "Fashion": dict(
        in_dim=[784, 784, 784],
        num_sample=10000,
        num_classes=10,
        num_views=3,
        batch_size=512,
        using_tsne=False,
    ),
    "BDGP": dict(
        in_dim=None,
        num_sample=None,
        num_classes=None,
        num_views=None,
        batch_size=256,
        using_tsne=False,
    ),
    "Reuters_dim10": dict(
        in_dim=None,
        num_sample=None,
        num_classes=None,
        num_views=None,
        batch_size=256,
        using_tsne=False,
    ),
    "Wikipedia": dict(
        in_dim=None,
        num_sample=None,
        num_classes=None,
        num_views=None,
        batch_size=256,
        using_tsne=False,
    ),
}


DATASET_ALIASES = {
    "BDGP": "BDGP",
    "Handwritten": "HandWritten",
    "HandWritten": "HandWritten",
    "Reuters": "Reuters_dim10",
    "Reuters_dim10": "Reuters_dim10",
    "Wikipedia": "Wikipedia",
}


def normalize_dataset_name(dataset_name):
    if dataset_name in DATASET_ALIASES:
        return DATASET_ALIASES[dataset_name]
    return dataset_name


def get_default_config(data_name):
    display_name = data_name
    data_name = normalize_dataset_name(data_name)
    if data_name not in DATASET_DEFAULTS:
        raise Exception("Undefined data_name")

    dataset_cfg = DATASET_DEFAULTS[data_name]
    return dict(
        Module=dict(
            in_dim=dataset_cfg["in_dim"],
            d_model=512,
            trans_dim=512,
            trans_layers=1,
            trans_headers=4,
            trans_dropout=0,
        ),
        Dataset=dict(
            name=data_name,
            display_name=display_name,
            data_dir="data",
            num_sample=dataset_cfg["num_sample"],
            num_classes=dataset_cfg["num_classes"],
            num_views=dataset_cfg["num_views"],
            missing_rate=0.5,
            batch_size=dataset_cfg["batch_size"],
            using_tsne=dataset_cfg["using_tsne"],
        ),
        training=dict(
            seed=0,
            lr=1.0e-3,
            epoch_tf=10,
            batch_size_tf=256,
            loss_target="heldout",
            freeze_embedding_layers=True,
        ),
        LLM=dict(
            provider="mock",
            model="mock-llm",
            llm_model="mock-llm",
            openai_model="gpt-4o-mini",
            openai_api_key_env="OPENAI_API_KEY",
            qwen_model="qwen-plus",
            qwen_api_key_env="DASHSCOPE_API_KEY",
            qwen_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
            qwen_timeout=60,
            qwen_max_retries=3,
            qwen_temperature=0.0,
            qwen_max_output_tokens=800,
            openai_timeout=60,
            openai_max_retries=3,
            openai_temperature=0.0,
            openai_max_output_tokens=800,
            use_structured_outputs=True,
            response_schema_version="semantic_recovery_v1",
            prompt_mode="fixed_template",
            output_dim=512,
            confidence_scale="1-10",
            cache_dir="outputs/llm_semantic_path/cache",
            cache_root="outputs/llm_cache",
            use_cache=True,
            force_refresh_cache=False,
            cache_only=False,
            max_samples=None,
            max_llm_queries=None,
            query_order="sequential",
            query_observed_views=False,
            temperature=0.0,
            resume=True,
            fail_fast=False,
            allow_partial=False,
            embedding_provider="mock",
            embedding_model="mock-embedding",
        ),
        Embedding=dict(
            provider="mock",
            model="mock-embedding",
            embedding_model="mock-embedding",
            openai_model="text-embedding-3-small",
            openai_api_key_env="OPENAI_API_KEY",
            qwen_model="text-embedding-v4",
            qwen_api_key_env="DASHSCOPE_API_KEY",
            qwen_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
            qwen_timeout=60,
            qwen_max_retries=3,
            openai_timeout=60,
            openai_max_retries=3,
            target_dim=None,
            use_dimensions_parameter=True,
            normalize_embedding=True,
            cache_root="outputs/embedding_cache",
            use_cache=True,
            force_refresh_cache=False,
            cache_only=False,
        ),
        Fusion=dict(
            mode="heuristic",
            gate_hidden_dim=128,
            abstention_threshold=0.3,
            preserve_observed=True,
            require_safe_stage2a=True,
            allow_partial_stage2a=False,
            output_root="outputs/fusion_gate",
        ),
        Evaluation=dict(
            representation="mean",
            normalize_representation=True,
            kmeans_n_init=20,
            kmeans_max_iter=300,
            kmeans_random_state=0,
            require_fusion_summary=True,
            require_non_debug_fusion=True,
            output_root="outputs/clustering_eval",
            comparison_methods=[
                "observed_only",
                "statistical_only",
                "llm_only",
                "fusion",
            ],
            comparison_output_root="outputs/comparison_eval",
            llm_missing_fallback="zero",
            save_method_representations=True,
        ),
        ClusteringHead=dict(
            head_type="dcp",
            input_source="fusion",
            output_root="outputs/clustering_head",
            epochs=100,
            batch_size=256,
            lr=1.0e-3,
            weight_decay=1.0e-4,
            representation="mean",
            normalize_input=True,
            projection_dim=512,
            use_projection=True,
            temperature=0.5,
            lambda_contrastive=1.0,
            lambda_kl=0.1,
            lambda_balance=0.01,
            warmup_epochs=10,
            update_target_every=1,
            init_cluster_centers="kmeans",
            eval_interval=5,
            save_interval=20,
            require_safe_stage2a=True,
            require_non_debug_fusion=True,
            allow_debug_fusion=False,
            train_input_tensor=False,
            save_representations=True,
        ),
        MethodRunner=dict(
            output_root="outputs/llm_gimvc_method",
            run_stage1=True,
            run_stage2a=True,
            run_stage2b=True,
            run_stage4a=True,
            reuse_existing=True,
            force_stage1=False,
            force_stage2a=False,
            force_stage2b=False,
            force_stage4a=False,
            provider="mock",
            embedding_provider="mock",
            gate_mode="heuristic",
            input_source="fusion",
            head_type="dcp",
            representation="mean",
            llm_missing_fallback="zero",
            allow_unsafe_stage2a=False,
            allow_debug_fusion=False,
            fail_fast=True,
            save_command_log=True,
            save_stage_summaries=True,
        ),
        Block1=dict(
            output_root="results/block1",
            datasets=["Reuters", "BDGP", "Wikipedia", "Handwritten"],
            missing_rates=[0, 10, 30, 50, 70, 90],
            missing_pattern="mcar",
            seeds=[0, 1, 2, 3, 4],
            runnable_methods=["llm_gimvc", "statistical_only"],
            reserved_methods=["mica", "jga_imvc", "freecsl"],
            methods=["llm_gimvc", "statistical_only"],
            metrics=["nmi", "ari", "acc", "purity"],
            provider="mock",
            embedding_provider="mock",
            gate_mode="heuristic",
            abstention_threshold=0.3,
            head_type="dcp",
            representation="mean",
            llm_missing_fallback="zero",
            epochs=100,
            batch_size=256,
            lr=1.0e-3,
            weight_decay=1.0e-4,
            temperature=0.5,
            lambda_contrastive=1.0,
            lambda_kl=0.1,
            lambda_balance=0.01,
            warmup_epochs=10,
            reuse_existing=True,
            force=False,
            fail_fast=True,
            allow_unsafe_stage2a=False,
            allow_debug_fusion=False,
            save_command_log=True,
            save_job_summary=True,
            save_resolved_config=True,
        ),
        ExternalBaselines=dict(
            output_root="results/external_baselines",
            data_root="results/baseline_data",
            repo_root="external_baselines",
            supported_methods=["mica", "jga_imvc", "freecsl"],
            export_formats=["npz", "mat"],
            default_export_format="npz",
            fail_if_repo_missing=True,
            fail_if_output_missing=True,
            allow_adapter_only=False,
            timeout_seconds=None,
            mica=dict(
                repo_dir="external_baselines/MICA",
                entrypoint="run_mica.py",
                command_template=(
                    "{python} {entrypoint} "
                    "--data {data_path} "
                    "--output {raw_output_dir} "
                    "--dataset {dataset} "
                    "--missing-rate {missing_rate_fraction} "
                    "--seed {seed}"
                ),
                expected_outputs=[
                    "pred_labels.npy",
                    "metrics.json",
                    "result.mat",
                    "result.csv",
                ],
            ),
            jga_imvc=dict(
                repo_dir="external_baselines/JGA-IMVC",
                entrypoint="run_jga_imvc.py",
                command_template=(
                    "{python} {entrypoint} "
                    "--data {data_path} "
                    "--output {raw_output_dir} "
                    "--dataset {dataset} "
                    "--missing-rate {missing_rate_fraction} "
                    "--seed {seed}"
                ),
                expected_outputs=[
                    "pred_labels.npy",
                    "metrics.json",
                    "result.mat",
                    "result.csv",
                ],
            ),
            freecsl=dict(
                repo_dir="external_baselines/FreeCSL",
                entrypoint="run_freecsl.py",
                command_template=(
                    "{python} {entrypoint} "
                    "--data {data_path} "
                    "--output {raw_output_dir} "
                    "--dataset {dataset} "
                    "--missing-rate {missing_rate_fraction} "
                    "--seed {seed}"
                ),
                expected_outputs=[
                    "pred_labels.npy",
                    "metrics.json",
                    "result.mat",
                    "result.csv",
                ],
            ),
        ),
    )
